spring.application.name=livraisons
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/livraison
spring.datasource.username=postgres
spring.datasource.password=poseidon
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=f3b0c4a2d5e6f7g8h9i09a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4
jwt.expiration=86400000 # 24 hours in milliseconds




# Activation des méthodes de paiement
payment.methods.enabled=CARTE_CREDIT,ORANGE_MONEY,MTN_MONEY,PAYPAL

# Configuration Orange Money
orange.money.api.key=votre-cle-api-orange
orange.money.api.url=https://api.orange.com/payment
orange.money.merchant.code=VOTRE_CODE_MARCHAND
orange.money.callback.url=https://votre-domaine.com/payment/callback

# Configuration MTN Mobile Money
mtn.money.api.key=votre-cle-api-mtn
mtn.money.api.url=https://api.mtn.com/v1/payment
mtn.money.merchant.id=VOTRE_ID_MARCHAND
mtn.money.callback.url=https://votre-domaine.com/payment/callback

# Configuration générale des paiements
payment.default.currency=XAF
payment.timeout=300000 # 5 minutes en millisecondes
# App


app.base-url=http://localhost:8083/api/